apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-serviceaccount-rbac
  namespace: dashboard-dev
subjects:
  - kind: ServiceAccount
    name: backend-serviceaccount
    namespace: dashboard-dev
roleRef:
  kind: ClusterRole
  name: cluster-admin # ezapp-manager-role
  apiGroup: rbac.authorization.k8s.io
