---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubik.fullname" . }}-files
  labels:
    {{- include "kubik.labels" . | nindent 4 }}
data:
{{- range .Values.appFiles }}
  {{ . }}: |-
{{ $.Files.Get (printf "dashboard/%s" .) | indent 4 }}
{{- end }}