apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubik.serviceAccountName" . }}-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: {{ include "kubik.serviceAccountName" . }}
    # Reference to upper's `metadata.namespace`
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: ezapp-manager-role # cluster-admin
  apiGroup: rbac.authorization.k8s.io
  