apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubik.serviceAccountName" . }}
  labels:
    {{- include "kubik.labels" . | nindent 4 }}
  annotations:
    {{- include "hpe-ezua.annotations" . | nindent 4 }}
