apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ printf "%s-%s-virtual-service" .Release.Name .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubik.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Values.ezua.virtualService.istioGateway | required "\nValid .Values.ezua.virtualService.istioGateway is required !\n" }}
  hosts:
    - {{ .Values.ezua.virtualService.endpoint | required "\nValid .Values.ezua.virtualService.endpoint is required !\n" }}
  http:
    - match:
        - uri:
            prefix: /
        - uri:
            exact: /
      rewrite:
        uri: /
      route:
        - destination:
            host: {{ include "kubik.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 3000
# API
    - match:
        - uri:
            prefix: /api
      rewrite:
        uri: /api
      route:
        - destination:
            host: {{ include "kubik.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8000

# WebSockets
    - match:
        - uri:
            prefix: /socket.io
      rewrite:
        uri: /socket.io
      route:
        - destination:
            host: {{ include "kubik.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8000
