apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: kubik-dev
  labels:
    app: kubik-frontend
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubik-frontend
  template:
    metadata:
      labels:
        app: kubik-frontend
    spec:
      containers:
        - name: frontend
          image: erdincka/kubik-frontend-dev
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://localhost:8000/api/v1"
            - name: NEXT_PUBLIC_WS_URL
              value: "http://localhost:8000"
            - name: NODE_ENV
              value: "development"
          resources:
            requests:
              cpu: "2000m"
              memory: "1Gi"
            limits:
              memory: "2Gi"
              cpu: "2000m"
