name: kubik
version: 1.0.0
apiVersion: v2
appVersion: v1.0.0
description: Admin Dashboard for PCAI
icon: https://raw.githubusercontent.com/kubernetes/website/main/static/images/kubernetes_logo.svg
keywords:
  - dashboard
  - kubernetes
  - admin
  - platform management
  - HPE
  - PCAI
type: application
