name: admindash
version: 0.1.7
apiVersion: v2
appVersion: v0.1.5
description: Admin Dashboard for PCAI
icon: https://raw.githubusercontent.com/kubernetes/website/main/static/images/kubernetes_logo.svg
keywords:
  - dashboard
  - kubernetes
  - admin
  - platform management
type: application
